name: Documentation

on:
  # Trigger on pushes to main branch
  push:
    branches: [ main ]
  # Trigger on PRs to main branch
  pull_request:
    branches: [ main ]


jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for proper versioning
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          
      - name: Setup doc deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Build documentation
        run: |
          mkdocs build
          
      - name: Check links
        run: |
          pip install linkchecker
          linkchecker site/
          
      - name: Deploy documentation
        if: github.event_name != 'pull_request'
        run: |
          mkdocs gh-deploy --force